### ISSUE TITLE
Vagrant-based examples not working

### ISSUE THREAD

**Issue by rjmccabe3701** [skydive-project/skydive#2132]
I am running through the [Multi-node and tunneling](http://skydive.network/tutorials/first-steps-5.html) example. 

I get this error in both MacOS Catalina and Ubuntu 18.04:

```bash
-> % vagrant up
/opt/vagrant/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): 'http://keystone-server.net/v2.0/tokens' (URI::InvalidURIError)
        from /opt/vagrant/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
        from /home/rjmccabe/.vagrant.d/gems/2.4.9/gems/vagrant-openstack-provider-0.13.0/lib/vagrant-openstack-provider/config.rb:514:in `valid_uri?'
        from /home/rjmccabe/.vagrant.d/gems/2.4.9/gems/vagrant-openstack-provider-0.13.0/lib/vagrant-openstack-provider/config.rb:468:in `block in validate'
        from /home/rjmccabe/.vagrant.d/gems/2.4.9/gems/vagrant-openstack-provider-0.13.0/lib/vagrant-openstack-provider/config.rb:467:in `each_pair'
        from /home/rjmccabe/.vagrant.d/gems/2.4.9/gems/vagrant-openstack-provider-0.13.0/lib/vagrant-openstack-provider/config.rb:467:in `validate'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/kernel_v2/config/vm.rb:757:in `validate'
        from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/config/v2/root.rb:71:in `block in validate'
...
```

If i make this change:

```diff
diff --git a/contrib/vagrant/Vagrantfile b/contrib/vagrant/Vagrantfile
index 27fb6bc8..3ad2d0d9 100644
--- a/contrib/vagrant/Vagrantfile
+++ b/contrib/vagrant/Vagrantfile
@@ -63,7 +63,7 @@ IFCFG
 end

 def populate_os_config(os, ip)
-  os.openstack_auth_url = ENV.fetch("OS_AUTH_URL", "'http://keystone-server.net/v2.0/tokens'")
+  os.openstack_auth_url = ENV.fetch("OS_AUTH_URL", "http://keystone-server.net/v2.0/tokens")
   os.username = ENV.fetch("OS_USERNAME", "openstackUser")
   os.password = ENV.fetch("OS_PASSWORD", "openstackPassword")
   os.tenant_name = ENV.fetch("OS_TENANT_NAME", "myTenant")
```

It seems to get further, but it complains about the domain name ``http://keystone-server.net/`` not being resolvable.  

I know next to nothing about vagrant, openstack or their configurations -- I just want to figure out what this project is about.  I do notice there is [this](https://github.com/skydive-project/skydive/tree/master/contrib/kubernetes) kubernetes example, but there is no tutorial to go along with it (kinda difficult to follow if I'm just getting started). 

What do u recommend as the first steps for a skydive beginner?

**Comment by safchain** [comment]
I submitted a fix here: https://github.com/skydive-project/skydive/pull/2133

**Comment by safchain** [comment]
I'm closing it as we merged fixes for this, feel free to re-open it if needed
