### ISSUE TITLE
api: panic if create noderule without name

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2213]
This call:
```
curl http://127.0.0.1:8082/api/noderule -d '{"Action": "create", "Metadata":{}}'
```
crashes the app

```
panic: interface conversion: interface {} is nil, not string

goroutine 316 [running]:
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).nodeID(...)
        /home/adrian/go/src/github.com/skydive-project/skydive/topology/enhancers/topology_manager.go:133
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).createNode(0xc0001202d0, 0xc000c30600, 0xc000a96068, 0x6)
        /home/adrian/go/src/github.com/skydive-project/skydive/topology/enhancers/topology_manager.go:137 +0x3ba
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).handleCreateNode(0xc0001202d0, 0xc000c30600, 0x0, 0x77)
        /home/adrian/go/src/github.com/skydive-project/skydive/topology/enhancers/topology_manager.go:182 +0x155
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).handleNodeRuleRequest(0xc0001202d0, 0xc000a96040, 0x3, 0x562d9a0, 0xc000c30600, 0x5, 0x76)
        /home/adrian/go/src/github.com/skydive-project/skydive/topology/enhancers/topology_manager.go:214 +0x7a
github.com/skydive-project/skydive/topology/enhancers.(*TopologyManager).onAPIWatcherEvent(0xc0001202d0, 0xc000a96040, 0x3, 0xc0006fc00a, 0x24, 0x562d9a0, 0xc000c30600)
        /home/adrian/go/src/github.com/skydive-project/skydive/topology/enhancers/topology_manager.go:258 +0x8c
github.com/skydive-project/skydive/graffiti/api/rest.(*BasicAPIHandler).AsyncWatch.func1(0xc00089ad80, 0x55629a0, 0xc00075d2c0, 0xc000a96be0, 0xa, 0xc000032390, 0xc000759460)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/api/rest/kv.go:196 +0x285
created by github.com/skydive-project/skydive/graffiti/api/rest.(*BasicAPIHandler).AsyncWatch
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/api/rest/kv.go:165 +0x34c
```

The create call assume that ``Type`` and ``Name`` keys will be available and [uses them](https://github.com/skydive-project/skydive/blob/6cd2cd18eca325ab6963bd0ca5d737e393710970/topology/enhancers/topology_manager.go#L132) without verification:
```
func (tm *TopologyManager) nodeID(node *types.NodeRule) graph.Identifier {
	return graph.GenID(node.Metadata["Type"].(string), node.Metadata["Name"].(string))
}
```

**Comment by lebauce** [comment]
Should be fixed by https://github.com/skydive-project/skydive/pull/2200. Could you please give it a try ?
