### ISSUE TITLE
The following settings shouldn't exist: qemu_use_session

### ISSUE THREAD

**Issue by oangit** [skydive-project/skydive#2216]
Hello.

http://skydive.network/tutorials/first-steps-5.html

vagrant up

```
vagrant up
Bringing machine 'agent1' up with 'libvirt' provider...
Bringing machine 'agent2' up with 'libvirt' provider...
Bringing machine 'analyzer1' up with 'libvirt' provider...
#<Thread:0x000055f8df6da3c0@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	 6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	 5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 1: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:18:in `call': There are errors in the configuration of this machine. Please fix (Vagrant::Errors::ConfigInvalid)
the following errors and try again:

Libvirt Provider:
* The following settings shouldn't exist: qemu_use_session

There are errors in the configuration of this machine. Please fix
the following errors and try again:

Libvirt Provider:
* The following settings shouldn't exist: qemu_use_session
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
```
libvirtd -V
libvirtd (libvirt) 4.0.0
```
```
vagrant version 
Installed Version: 2.0.2
```
```
vagrant plugin list
vagrant-libvirt (0.0.43, system)
```
Could you explain what this mistake is?
How to fix it?

**Comment by lebauce** [comment]
@oangit It may be because your Vagrant version is too old. Could you please try with a newer version ?

**Comment by safchain** [comment]
Do you still have an issue with this ? or can we close it ?
