### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2252]
I have skydive analyzer running and two clients.

One client is a custom python script writing nodes and edges.
The other client is the new react UI.

Each hour (*:42) the "writter" start its process that could take some minutes to complete (it is reading from a slow source).

Looks like at the same time someone connected to the UI, requesting the graph with certain filters and that triggered the fatal error:
```
2020-07-10T08:42:04.485Z        INFO       common/subscriber_endpoint.go:155 (*SubscriberEndpoint).OnStructMessage ANALYZERHOST: Client 127.0.0.1:47494 requested subscription with filter G.V().Has('Type', 'Category').HasEither('Description', 'Operaciones',).Out('Type', 'Service').HasEither('Description', 'Servicio',).Out('Type', 'Component').HasEither('Description', 'AAA','Description', 'BB','Description', 'CC','Description', 'DD','Description', 'EE','Description', 'FF',).Out('Type', 'Instance').HasEither('Description', 'AA [Producción]','Description', 'BB [Producción]','Description', 'CC [Producción]','Description', 'DD [Producción]','Description', 'EE [Producción]','Description', 'FF [Producción]',).Descendants(30).As('Selection').Dedup().SubGraph()
2020-07-10T08:42:08.036Z        INFO       elasticsearch/client.go:107 InfoLogger.Printf   ANALYZERHOST: [POST https://172.30.170.112:9200/_bulk %!s(int=200) %!s(float64=0.098)] %!s(MISSING) [status:%!d(MISSING), request:%!f(MISSING)s]
2020-07-10T08:42:12.993Z        INFO       elasticsearch/client.go:107 InfoLogger.Printf   ANALYZERHOST: [POST https://172.30.170.110:9200/_bulk %!s(int=200) %!s(float64=0.029)] %!s(MISSING) [status:%!d(MISSING), request:%!f(MISSING)s]
2020-07-10T08:42:18.002Z        INFO       elasticsearch/client.go:107 InfoLogger.Printf   ANALYZERHOST: [POST https://172.30.170.111:9200/_bulk %!s(int=200) %!s(float64=0.062)] %!s(MISSING) [status:%!d(MISSING), request:%!f(MISSING)s]
fatal error: concurrent map iteration and map write

goroutine 324071 [running]:
runtime.throw(0x540e13e, 0x26)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00343f620 sp=0xc00343f5f0 pc=0x1f507c2
runtime.mapiternext(0xc00343f720)
        /usr/local/go/src/runtime/map.go:853 +0x552 fp=0xc00343f6a0 sp=0xc00343f620 pc=0x1f2b5c2
github.com/skydive-project/skydive/graffiti/graph.(*MemoryBackend).GetNodeEdges(0xc00044fa60, 0xc0018e4090, 0x0, 0x203001, 0x58d9c60, 0xc0017dcfc0, 0xc00343f860, 0x1f28376, 0xc0017b17a0)
        /go/src/github.com/skydive-project/skydive/graffiti/graph/memory.go:150 +0xf1 fp=0xc00343f790 sp=0xc00343f6a0 pc=0x25e3ed1
github.com/skydive-project/skydive/graffiti/graph.(*CachedBackend).GetNodeEdges(0xc0004d81b0, 0xc0018e4090, 0x0, 0xc0017b1701, 0x58d9c60, 0xc0017dcfc0, 0xc00199dc00, 0x7f1b3f9fe7d0, 0x0)
        /go/src/github.com/skydive-project/skydive/graffiti/graph/cachedbackend.go:98 +0xb2 fp=0xc00343f7f8 sp=0xc00343f790 pc=0x25cf762

```

**Comment by adrianlzt** [comment]
Full stack trace
[skydive_fatal_trace.txt](https://github.com/skydive-project/skydive/files/4902093/skydive_fatal_trace.txt)

**Comment by adrianlzt** [comment]
If I understand correctly, the problem is go [iterating](https://github.com/datadope-io/skydive/blob/feature/rest_api_partial_update/graffiti/graph/memory.go#L150), goroutine 324071:
```go
		for _, e := range n.edges {
			if e.MatchMetadata(meta) {
				edges = append(edges, e.Edge)
			}
		}
```

While some other process is modifying that ``n.edges``

**Comment by adrianlzt** [comment]
Dumb program that generates the same error
```go
package main

import (
	"time"
)

func main() {
	mymap := map[int]int{1: 1, 2: 2}
	go func() {
		for range mymap {
			time.Sleep(1 * time.Second)
		}
	}()

	go func() {
		for {
			mymap[10] = 10
		}
	}()

	time.Sleep(2 * time.Second)
}
```

**Comment by safchain** [comment]
I mean that a graph.Lock is missing somewhere. What API the python script is using ?

**Comment by adrianlzt** [comment]
API REST.
The modifications I did

**Comment by safchain** [comment]
Sorry can you point me the modifications please ? The stack trace shows the iterating part but not the writing thing I guess this is probably in the modifications or in the call path of the REST API call

**Comment by adrianlzt** [comment]
I think could be a problem of my PR handling incorrectly the edges update.
https://github.com/skydive-project/skydive/pull/2234/files#diff-9f82f6189ba2de04ad86a47743ae358aR109

I will fix this like in "node"

**Comment by safchain** [comment]
It seems that none of the function of the handler are protecting the graph read/update with locks.

**Comment by adrianlzt** [comment]
To reproduce the issue I have:

- created 100 nodes
- continuously create edges between node "1" and the rest of them
- continuously query descendants of node "1"

```sh
# create nodes
for i in $(seq 1 1000); do
curl 127.0.0.1:8082/api/node -H "Content-Type: application/json" -d "{\"ID\": \"${i}\", \"CreatedAt\": $(date +%s%3N), \"UpdatedAt\": $(date +%s%3N), \"Metadata\": {\"Name\": \"foo\", \"Type\": \"bar\"}}"
done
```

```sh
# create edges
for i in $(seq 2 1000); do
  for to in $(seq 2 100); do
    curl 127.0.0.1:8082/api/edge -H "Content-Type: application/json" -d \
      "{\"ID\": \"from: 1 (${i}) -> ${to}\", \"CreatedAt\": $(date +%s%3N), \"UpdatedAt\": $(date +%s%3N), \"Origin\": \"CMDB-Syncer\", \"Metadata\": {\"RelationType\": \"ownership\"}, \"Child\": \"$to\", \"Parent\": \"1\"}"
  done
done
```

```sh
# query
while true; do
  curl -sSf 127.0.0.1:8082/api/topology -H "Content-Type: application/json" -d '{"GremlinQuery": "G.V(\"1\").Descendants(3)"}' > /dev/null
done
```

**Comment by adrianlzt** [comment]
I was trying to make a test with this, but having troubles with #2256

**Comment by lebauce** [comment]
https://github.com/skydive-project/skydive/pull/2260
