### ISSUE TITLE
Broken functional tests

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2256]
With the latest master (ea781bd) I am unable to run the functional tests:
```sh
➜ make functional TEST_PATTERN=AlertAPI
make test.functionals VERBOSE=true TIMEOUT=10m ARGS='-standalone -analyzer.topology.backend elasticsearch -analyzer.flow.backend elasticsearch' TEST_PATTERN="AlertAPI"
make[1]: se entra en el directorio '/home/adrian/go/src/github.com/skydive-project/skydive'
go test -tags " lxd libvirt opencontrail packetinject opencontrail test" -race  -v -timeout 10m -c -o tests/functionals ./tests/
for functest in TestAlertAPI ; do \
        make ARGS="-test.run $functest$\$ -standalone -analyzer.topology.backend elasticsearch -analyzer.flow.backend elasticsearch" test.functionals.run EXTRA_ARGS="-analyzer.topology.probes= -agent.topology.probes=opencontrail"; \
done
make[2]: se entra en el directorio '/home/adrian/go/src/github.com/skydive-project/skydive'
cd tests && sudo -E ./functionals -test.v -test.run "AlertAPI" -test.timeout 10m -test.run TestAlertAPI$ -standalone -analyzer.topology.backend elasticsearch -analyzer.flow.backend elasticsearch -analyzer.topology.probes= -agent.topology.probes=opencontrail
Config: ---
http:
  ws:
    pong_timeout: 10

analyzers:
  - 127.0.0.1:64500

analyzer:
  listen: 0.0.0.0:64500
  flow:
    backend: elasticsearch
  analyzer_username: admin
  analyzer_password: password
  topology:
    backend: elasticsearch
    probes:

  startup:
    capture_gremlin: "g.V().Has('Name','startup-vm2')"

agent:
  listen: 0.0.0.0:64499
  topology:
    probes:
    - ovsdb
    - blockdev
    - docker
    - lxd
    - lldp
    - runc
    - socketinfo
    - libvirt
    - opencontrail

    netlink:
      metrics_update: 5
    lldp:
      interfaces:
      - lldp0

  metadata:
    mydict:
      value: 123
    myarrays:
      integers:
      - 1
      - 2
      - 3
      bools:
      - true
      - true
      strings:
      - dog
      - cat
      - frog

flow:
  expire: 600
  update: 10

ovs:
  oflow:
    enable: true
    native: false
    address:
      br-test: tcp:127.0.0.1:16633

storage:
  orientdb:
    addr: http://127.0.0.1:2480
    database: Skydive
    username: root
    password:
  elasticsearch:
    host: 127.0.0.1:9201

logging:
  level: DEBUG
  syslog:
    address: /tmp/skydive-test-syslog

etcd:
  data_dir: /tmp/skydive-etcd
  embedded: true
  servers:
    - http://localhost:12379

2020-07-13T12:04:14.150+0200    DEBUG   config/rbac.go:50 (*logger).Print       archer: Model:
2020-07-13T12:04:14.151+0200    DEBUG   config/rbac.go:50 (*logger).Print       archer: Model:
2020-07-13T12:04:14.151+0200    DEBUG   config/rbac.go:54 (*logger).Printf      archer: r.r: sub, obj, act
2020-07-13T12:04:14.151+0200    DEBUG   config/rbac.go:54 (*logger).Printf      archer: p.p: sub, obj, act, eft
2020-07-13T12:04:14.151+0200    DEBUG   config/rbac.go:54 (*logger).Printf      archer: e.e: some(where (p_eft == allow)) && !some(where (p_eft == deny))
2020-07-13T12:04:14.151+0200    DEBUG   config/rbac.go:54 (*logger).Printf      archer: m.m: g(r_sub, p_sub) && r_obj == p_obj && r_act == p_act
2020-07-13T12:04:14.151+0200    DEBUG   config/rbac.go:54 (*logger).Printf      archer: g.g: _, _
2020-07-13T12:04:14.155+0200    DEBUG   config/rbac.go:50 (*logger).Print       archer: Role links for: g
2020-07-13T12:04:14.155+0200    DEBUG   config/rbac.go:50 (*logger).Print       archer:
2020-07-13T12:04:14.156+0200    INFO    analyzer/storage.go:60 newGraphBackendFromConfig        archer: Using elasticsearch (driver elasticsearch) as graph storage backend
2020-07-13T12:04:14.160+0200    INFO    plugin/topology.go:47 LoadTopologyPlugins       archer: Topology plugins: []
2020-07-13T12:04:14.163+0200    INFO    analyzer/storage.go:115 newFlowBackendFromConfig        archer: Using elasticsearch (driver elasticsearch) as flow storage backend
2020-07-13T12:04:14.178+0200    INFO    server/flow_server.go:217 NewFlowServerUDPConn  archer: Analyzer listen agents on UDP socket
2020-07-13 12:04:14.407358 I | embed: listening for peers on http://127.0.0.1:12380
2020-07-13 12:04:14.407452 I | embed: listening for client requests on 127.0.0.1:12379
fatal error: checkptr: unsafe pointer conversion

goroutine 1 [running]:
runtime.throw(0x746853c, 0x23)
        /usr/lib/go/src/runtime/panic.go:1116 +0x72 fp=0xc000d5fd58 sp=0xc000d5fd28 pc=0x1fa39f2
runtime.checkptrAlignment(0xc000077970, 0x70a2820, 0x1)
        /usr/lib/go/src/runtime/checkptr.go:20 +0xc9 fp=0xc000d5fd88 sp=0xc000d5fd58 pc=0x1f749e9
github.com/coreos/bbolt.(*Bucket).write(0xc000d5ff00, 0x0, 0x0, 0x0)
        /home/adrian/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/bucket.go:624 +0x15c fp=0xc000d5fdf0 sp=0xc000d5fd88 pc=0x64b493c
github.com/coreos/bbolt.(*Bucket).CreateBucket(0xc00020a398, 0xa772904, 0x7, 0x7, 0x6907e90, 0x7effe8910008, 0xc0009f6720)
        /home/adrian/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/bucket.go:181 +0x465 fp=0xc000d5ffb0 sp=0xc000d5fdf0 pc=0x64b0d85
github.com/coreos/bbolt.(*Tx).CreateBucket(...)
        /home/adrian/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/tx.go:108
github.com/coreos/etcd/mvcc/backend.(*batchTx).UnsafeCreateBucket(0xc0009f6720, 0xa772904, 0x7, 0x7)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/mvcc/backend/batch_tx.go:48 +0x99 fp=0xc000d60040 sp=0xc000d5ffb0 pc=0x6516d39
github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).UnsafeCreateBucket(0xc0009f6720, 0xa772904, 0x7, 0x7)
        <autogenerated>:1 +0x62 fp=0xc000d60070 sp=0xc000d60040 pc=0x651ea52
github.com/coreos/etcd/etcdserver/membership.mustCreateBackendBuckets(0x7c5ffa0, 0xc000221730)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/etcdserver/membership/store.go:166 +0x109 fp=0xc000d60108 sp=0xc000d60070 pc=0x65cf759
github.com/coreos/etcd/etcdserver/membership.(*RaftCluster).SetBackend(...)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/etcdserver/membership/cluster.go:203
github.com/coreos/etcd/etcdserver.NewServer(0xc0001b2f70, 0x6, 0x0, 0x0, 0x0, 0x0, 0xc00046e980, 0x1, 0x1, 0xc00046eb80, ...)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/etcdserver/server.go:363 +0x42bf fp=0xc000d60d98 sp=0xc000d60108 pc=0x66aafff
github.com/coreos/etcd/embed.StartEtcd(0xc000522c00, 0xc00002e000, 0x0, 0x0)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/embed/etcd.go:179 +0xd97 fp=0xc000d61ae0 sp=0xc000d60d98 pc=0x681cab7
github.com/skydive-project/skydive/graffiti/etcd/server.(*EmbeddedServer).Start(0xc000168c00, 0xc000232540, 0x7c2d7e0)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/etcd/server/server.go:128 +0x7f fp=0xc000d61d00 sp=0xc000d61ae0 pc=0x6829a0f
github.com/skydive-project/skydive/analyzer.(*Server).Start(0xc000232540, 0x0, 0x0)
        /home/adrian/go/src/github.com/skydive-project/skydive/analyzer/server.go:131 +0x372 fp=0xc000d61d80 sp=0xc000d61d00 pc=0x68649e2
github.com/skydive-project/skydive/tests.runStandalone()
        /home/adrian/go/src/github.com/skydive-project/skydive/tests/tests.go:862 +0x94 fp=0xc000d61dc0 sp=0xc000d61d80 pc=0x687f294
github.com/skydive-project/skydive/tests.setupTests(0xc00046e200)
        /home/adrian/go/src/github.com/skydive-project/skydive/tests/tests.go:929 +0x234 fp=0xc000d61f00 sp=0xc000d61dc0 pc=0x687f5a4
github.com/skydive-project/skydive/tests.TestMain(...)
        /home/adrian/go/src/github.com/skydive-project/skydive/tests/alert_test.go:467
main.main()
        _testmain.go:260 +0x225 fp=0xc000d61f88 sp=0xc000d61f00 pc=0x68e6b05
runtime.main()
        /usr/lib/go/src/runtime/proc.go:203 +0x1fa fp=0xc000d61fe0 sp=0xc000d61f88 pc=0x1fa6d5a
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000d61fe8 sp=0xc000d61fe0 pc=0x1fd9081

goroutine 35 [select]:
github.com/pmylund/go-cache.(*janitor).Run(0xc000245cb0, 0xc000276800)
        /home/adrian/go/pkg/mod/github.com/pmylund/go-cache@v0.0.0-20170722040110-a3647f8e31d7/cache.go:1079 +0x151
created by github.com/pmylund/go-cache.runJanitor
        /home/adrian/go/pkg/mod/github.com/pmylund/go-cache@v0.0.0-20170722040110-a3647f8e31d7/cache.go:1099 +0x101

goroutine 97 [select]:
github.com/skydive-project/skydive/js.(*Runtime).runEventLoop(0xc000277e00)
        /home/adrian/go/src/github.com/skydive-project/skydive/js/runtime.go:213 +0x245
created by github.com/skydive-project/skydive/js.(*Runtime).Start
        /home/adrian/go/src/github.com/skydive-project/skydive/js/runtime.go:339 +0x4d

goroutine 125 [select]:
github.com/pmylund/go-cache.(*janitor).Run(0xc00038b4b0, 0xc000156440)
        /home/adrian/go/pkg/mod/github.com/pmylund/go-cache@v0.0.0-20170722040110-a3647f8e31d7/cache.go:1079 +0x151
created by github.com/pmylund/go-cache.runJanitor
        /home/adrian/go/pkg/mod/github.com/pmylund/go-cache@v0.0.0-20170722040110-a3647f8e31d7/cache.go:1099 +0x101

goroutine 24 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0xa9a6240)
        /home/adrian/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1018 +0xae
created by k8s.io/klog.init.0
        /home/adrian/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:404 +0x9b

goroutine 102 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00000e260)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/pkg/logutil/merge_logger.go:173 +0x4b2
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/pkg/logutil/merge_logger.go:91 +0xfc

goroutine 29 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00071b960)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/pkg/logutil/merge_logger.go:173 +0x4b2
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/pkg/logutil/merge_logger.go:91 +0xfc

goroutine 91 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00045b880)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/pkg/logutil/merge_logger.go:173 +0x4b2
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/pkg/logutil/merge_logger.go:91 +0xfc

goroutine 176 [select]:
github.com/pmylund/go-cache.(*janitor).Run(0xc0003f07c0, 0xc000156780)
        /home/adrian/go/pkg/mod/github.com/pmylund/go-cache@v0.0.0-20170722040110-a3647f8e31d7/cache.go:1079 +0x151
created by github.com/pmylund/go-cache.runJanitor
        /home/adrian/go/pkg/mod/github.com/pmylund/go-cache@v0.0.0-20170722040110-a3647f8e31d7/cache.go:1099 +0x101

goroutine 178 [select]:
github.com/skydive-project/skydive/js.(*Runtime).runEventLoop(0xc0007151c0)
        /home/adrian/go/src/github.com/skydive-project/skydive/js/runtime.go:213 +0x245
created by github.com/skydive-project/skydive/js.(*Runtime).Start
        /home/adrian/go/src/github.com/skydive-project/skydive/js/runtime.go:339 +0x4d

goroutine 180 [select]:
github.com/coreos/etcd/mvcc/backend.(*backend).run(0xc000221730)
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/mvcc/backend/backend.go:267 +0x262
created by github.com/coreos/etcd/mvcc/backend.newBackend
        /home/adrian/go/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/mvcc/backend/backend.go:161 +0x43d
make[2]: *** [.mk/tests.mk:79: test.functionals.run] Error 2
make[2]: se sale del directorio '/home/adrian/go/src/github.com/skydive-project/skydive'
make[1]: *** [.mk/tests.mk:91: test.functionals] Error 2
make[1]: se sale del directorio '/home/adrian/go/src/github.com/skydive-project/skydive'
make: *** [.mk/tests.mk:97: functional] Error 2
```

**Comment by lebauce** [comment]
https://github.com/skydive-project/skydive/pull/2260

**Comment by lebauce** [comment]
https://github.com/skydive-project/skydive/pull/2262
