### ISSUE TITLE
Elasticsearch - failed to execute bulk item (index)

### ISSUE THREAD

**Issue by mnasiadka** [skydive-project/skydive#462]
[2017-09-26 13:17:08,157][DEBUG][action.bulk              ] [146.213.169.166] [skydive_v7][0] failed to execute bulk item (index) index {[skydive][node][c270268e-94e7-464f-7045-269068cd63a2-28], source[{"CreatedAt":1506431225394,"Host":"ucsubu4000","ID":"c270268e-94e7-464f-7045-269068cd63a2","Metadata":{"Driver":"veth","EncapType":"ether","ExtID":{"attached-mac":"fa:16:3e:10:db:73","iface-id":"87306718-b5c5-406d-bbca-d0ece55c3b94","iface-status":"active","vm-uuid":"98c8c21a-1720-4f07-b6bf-111f30ae7147"},"FDB":[{"Flags":2,"MAC":"33:33:00:00:00:01","State":128,"Type":0},{"Flags":2,"MAC":"01:00:5e:00:00:01","State":128,"Type":0},{"Flags":2,"MAC":"33:33:ff:0b:84:78","State":128,"Type":0}],"IPV6":["fe80::285c:d1ff:fe0b:8478/64"],"IPs":"192.168.2.19","IfIndex":118,"LastMetric":{"Collisions":0,"Last":1506431825468,"Multicast":0,"RxBytes":38868,"RxCompressed":0,"RxCrcErrors":0,"RxDropped":0,"RxErrors":0,"RxFifoErrors":0,"RxFrameErrors":0,"RxLengthErrors":0,"RxMissedErrors":0,"RxOverErrors":0,"RxPackets":290,"Start":1506431795468,"TxAbortedErrors":0,"TxBytes":106872,"TxCarrierErrors":0,"TxCompressed":0,"TxDropped":0,"TxErrors":0,"TxFifoErrors":0,"TxHeartbeatErrors":0,"TxPackets":475,"TxWindowErrors":0},"MAC":"2a:5c:d1:0b:84:78","MTU":1500,"Manager":"neutron","Name":"qvo87306718-b5","NetworkID":"e95dbb73-fd77-4036-a72f-448f560f75b0","NetworkName":"magnum","Neutron":{"ExtID.attached-mac":"fa:16:3e:10:db:73","ExtID.vm-uuid":"98c8c21a-1720-4f07-b6bf-111f30ae7147","IPs":"192.168.2.19","NetworkID":"e95dbb73-fd77-4036-a72f-448f560f75b0","NetworkName":"magnum","PortID":"87306718-b5c5-406d-bbca-d0ece55c3b94","TenantID":"14f2811fc3ff4da99f555c7627574049"},"OfPort":51,"PeerIfIndex":119,"PortID":"87306718-b5c5-406d-bbca-d0ece55c3b94","Speed":10000,"State":"UP","Statistics":{"Collisions":0,"Multicast":0,"RxBytes":201872604,"RxCompressed":0,"RxCrcErrors":0,"RxDropped":0,"RxErrors":0,"RxFifoErrors":0,"RxFrameErrors":0,"RxLengthErrors":0,"RxMissedErrors":0,"RxOverErrors":0,"RxPackets":1693907,"TxAbortedErrors":0,"TxBytes":2398499724,"TxCarrierErrors":0,"TxCompressed":0,"TxDropped":0,"TxErrors":0,"TxFifoErrors":0,"TxHeartbeatErrors":0,"TxPackets":6103663,"TxWindowErrors":0},"TID":"9f0844d3-352a-52b5-55bd-6b04ebd906aa","TenantID":"14f2811fc3ff4da99f555c7627574049","Type":"veth","UUID":"8b453e76-940d-4775-ae8d-43e346c4c1aa"},"Revision":28,"UpdatedAt":1506431825481}]}
MapperParsingException[Field name [ExtID.attached-mac] cannot contain '.']
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:277)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:222)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:197)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:309)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:222)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:197)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:309)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:222)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:549)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by safchain** [comment]
which version of Elasticsearch and Skydive are you using ?

**Comment by mnasiadka** [comment]
$ dpkg -l | grep elasticsearch
ii  elasticsearch                  2.4.6                                 all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html

Skydive 0.12.0 from https://github.com/skydive-project/skydive/releases/download/v0.12.0/skydive

**Comment by safchain** [comment]
It seems that this bug has been already fixed by https://github.com/skydive-project/skydive/commit/f010aec562200aef936c1781a3904e64b8d20968 which is not is the 0.12 release.
Until the new release maybe you could test with the master binary : https://github.com/skydive-project/skydive-binaries/blob/travis-builds/skydive-latest

**Comment by safchain** [comment]
Closing for now, please re-open it if having the issue again
